export const QueConf = {
  comments: {
    lineComment: ";",
  },

  brackets: [
    ["(", ")"],
    ["{", "}"],
    ["[", "]"],
  ],

  autoClosingPairs: [
    { open: "{", close: "}" },
    { open: "[", close: "]" },
    { open: "(", close: ")" },
    { open: '"', close: '"' },
  ],

  surroundingPairs: [
    { open: "{", close: "}" },
    { open: "[", close: "]" },
    { open: "(", close: ")" },
    { open: '"', close: '"' },
  ],
};

export const Que = {
  defaultToken: "",
  ignoreCase: true,
  tokenPostfix: ".scheme",

  brackets: [
    { open: "(", close: ")", token: "delimiter.parenthesis" },
    { open: "{", close: "}", token: "delimiter.curly" },
    { open: "[", close: "]", token: "delimiter.square" },
  ],
  typeKeywords: ["Bool", "Int", "Float", "Char"],

  operators: [
    "=",
    ">",
    "<",
    "!",
    "#",
    "~",
    "!",
    "?",
    ":",
    "==",
    "<=",
    ">=",
    "!=",
    "|>",
    "++",
    "--",
    "**",
    "+",
    "-",
    "*",
    "/",
    "&",
    "|",
    "^",
    "%",
    ".",
    "<<",
    ">>",
    "+=",
    "-=",
    "*=",
    "/=",
  ],

  keywords: [
    "do",
    "let",
    "let~",
    "let*",
    "loop",
    "if",
    "unless",
    "cond",
    "lambda",
    "mod",
    "length",
    "as",
    "get",
    "at",
    "set!",
    "pop!",
    "push!",
    "pull!",
    "swap!",
    "emod",
    "not",
    "and",
    "or",
    "identity",
    "boole-set",
    "boole-eqv",
    "eq",
    "true?",
    "false?",
    "integer",
    "floating",
    "boolean",
    "variable",
    "que",
    "string",
    "chars",
    "digits",
    "set",
    "vector",
    "bigint",
    "tuple",
    "table",
    "fst",
    "snd",
    "car",
    "cdr",
    "has?",
    "in-bounds?",
    "apply",
    "eq?",
    "comp",
    "matrix",
    "type",
  ],

  constants: [
    // Not sure about these
    "enumerate",
    "sum",
    "nl", // new line
    "sp", // space
    "ep", // empty
    "dq", // doublequote
    "sq", // singlequote
    "bt", // backtick
    "map",
    "filter",
    "reduce",
    "every?",
    "some?",
    "empty?",
    "empty!",
    "copy",
    "reverse",
    "slice",
    "cons",
    "sort!",
    "sort",
    "range",
    "square",
    "sqrt",
    "expt",
    "floor",
    "ceil",
    "max",
    "min",
    "abs",
    "first",
    "last",
    "count",
    "points",
    "zip",
    "unzip",
    "permutation",
    "window",
    "flat",
    "pair",
    "product",
    "find",
    "lcm",
    "gcd",
    "call",
    "odd?",
    "even?",
    "upper",
    "lower",
    "match?",
    "digit?",
    "fill",
    "take",
    "drop",
    "clamp",
    "one?",
    "zero?",
    "ones",
    "zeroes",
    "positive?",
    "negative?",
    "invert",
    "divisible?",
    "maximum",
    "minimum",
    "for",
    "subset",
    "scan",
    "extreme",
    "neighborhood",
    "unique",
    "transpose",
    "interleave",
    "intersperse",
    "cycle",
    "replicate",
    "avg",
    "mean",
    "median",
    "each",
    "const",
    "select",
    "exclude",
    "group",
    "append!",
    "tail",
    "head",
  ],
  boolean: ["true", "false", "nil", "infinity"],
  tokenizer: {
    root: [
      [/[0-9]+/, "number"],
      // [/^-?(?:\d+|\d+.\d+)$/, "number"],

      // @ annotations.
      //   [/@\/\s*[a-zA-Z_\$][\w\$]*/, "annotation"],
      //   [
      //     /(?:\b(?:(define|define-syntax|define-macro))\b)(\s+)((?:\w|\-|\!|\?)*)/,
      //     ["keyword", "white", "variable"],
      //   ],

      { include: "@whitespace" },
      { include: "@strings" },

      [
        /[a-za-z_#][a-zA-Z0-9_\?\!\*\~]*/,
        {
          cases: {
            "@boolean": "boolean",
            "@constants": "constant",
            "@keywords": "keyword",
            "@typeKeywords": "type",
            "@operators": "operators",
            "@default": "identifier",
          },
        },
      ],
    ],

    comment: [
      [/[^\|#]+/, "comment"],
      [/#\|/, "comment", "@push"],
      [/\|#/, "comment", "@pop"],
      [/[\|#]/, "comment"],
    ],

    whitespace: [
      [/[ \t\r\n]+/, "white"],
      [/#\|/, "comment", "@comment"],
      [/;.*$/, "comment"],
    ],

    strings: [
      [/"/, "string", "@string_multi"], // characters
      [/'[^\\']'/, "string"],
    ],

    string_multi: [
      [/[^\\"$]+/, "string"],
      [/"/, "string", "@pop"],
    ],
  },
};
