export const standardLibrary = [
  ["+", "Int -> Int -> Int"],
  ["+#", "Char -> Char -> Char"],
  ["+.", "Float -> Float -> Float"],
  ["-", "Int -> Int -> Int"],
  ["-#", "Char -> Char -> Char"],
  ["-.", "Float -> Float -> Float"],
  ["/", "Int -> Int -> Int"],
  ["/#", "Char -> Char -> Char"],
  ["/.", "Float -> Float -> Float"],
  ["*", "Int -> Int -> Int"],
  ["*#", "Char -> Char -> Char"],
  ["*.", "Float -> Float -> Float"],
  ["mod", "Int -> Int -> Int"],
  ["mod.", "Float -> Float -> Float"],
  ["=", "Int -> Int -> Bool"],
  ["=?", "Bool -> Bool -> Bool"],
  ["=#", "Char -> Char -> Bool"],
  ["=.", "Float -> Float -> Bool"],
  ["<", "Int -> Int -> Bool"],
  ["<#", "Char -> Char -> Bool"],
  ["<.", "Float -> Float -> Bool"],
  [">", "Int -> Int -> Bool"],
  [">#", "Char -> Char -> Bool"],
  [">.", "Float -> Float -> Bool"],
  ["<=", "Int -> Int -> Bool"],
  ["<=#", "Char -> Char -> Bool"],
  ["<=.", "Float -> Float -> Bool"],
  [">=", "Int -> Int -> Bool"],
  [">=#", "Char -> Char -> Bool"],
  [">=.", "Float -> Float -> Bool"],
  ["not", "Bool -> Bool"],
  ["and", "Bool -> Bool -> Bool"],
  ["or", "Bool -> Bool -> Bool"],
  ["^", "Int -> Int -> Int"],
  [">>", "Int -> Int -> Int"],
  ["<<", "Int -> Int -> Int"],
  ["|", "Int -> Int -> Int"],
  ["&", "Int -> Int -> Int"],
  ["~", "Int -> Int"],
  ["true", "Bool"],
  ["false", "Bool"],
  ["car", "[T13] -> T13"],
  ["cdr", "[T13] -> Int -> [T13]"],
  ["Int->Float", "Int -> Float"],
  ["Float->Int", "Float -> Int"],
  ["*Id*", "[Int]"],
  ["Id", "() -> Int"],
  ["const/int/max-safe", "Int"],
  ["const/int/min-safe", "Int"],
  ["const/float/max-safe", "Float"],
  ["const/float/min-safe", "Float"],
  ["const/float/pi", "Float"],
  ["infinity", "Int"],
  ["-infinity", "Int"],
  ["Int", "Int"],
  ["Float", "Float"],
  ["Char", "Char"],
  ["Bool", "Bool"],
  ["nil", "()"],
  ["Nil", "()"],
  ["as", "T15 -> T16 -> T16"],
  [":", "T15 -> T15 -> T15"],
  ["eq", "Bool -> Bool -> Bool"],
  ["identity", "T14 -> T14"],
  ["Char/nil", "Char"],
  ["Char/start", "Char"],
  ["Char/end", "Char"],
  ["std/char/A", "Char"],
  ["std/char/B", "Char"],
  ["std/char/C", "Char"],
  ["std/char/D", "Char"],
  ["std/char/E", "Char"],
  ["std/char/F", "Char"],
  ["std/char/G", "Char"],
  ["std/char/H", "Char"],
  ["std/char/I", "Char"],
  ["std/char/J", "Char"],
  ["std/char/K", "Char"],
  ["std/char/L", "Char"],
  ["std/char/M", "Char"],
  ["std/char/N", "Char"],
  ["std/char/O", "Char"],
  ["std/char/P", "Char"],
  ["std/char/Q", "Char"],
  ["std/char/R", "Char"],
  ["std/char/S", "Char"],
  ["std/char/T", "Char"],
  ["std/char/U", "Char"],
  ["std/char/V", "Char"],
  ["std/char/W", "Char"],
  ["std/char/X", "Char"],
  ["std/char/Y", "Char"],
  ["std/char/Z", "Char"],
  ["std/char/a", "Char"],
  ["std/char/b", "Char"],
  ["std/char/c", "Char"],
  ["std/char/d", "Char"],
  ["std/char/e", "Char"],
  ["std/char/f", "Char"],
  ["std/char/g", "Char"],
  ["std/char/h", "Char"],
  ["std/char/i", "Char"],
  ["std/char/j", "Char"],
  ["std/char/k", "Char"],
  ["std/char/l", "Char"],
  ["std/char/m", "Char"],
  ["std/char/n", "Char"],
  ["std/char/o", "Char"],
  ["std/char/p", "Char"],
  ["std/char/q", "Char"],
  ["std/char/r", "Char"],
  ["std/char/s", "Char"],
  ["std/char/t", "Char"],
  ["std/char/u", "Char"],
  ["std/char/v", "Char"],
  ["std/char/w", "Char"],
  ["std/char/x", "Char"],
  ["std/char/y", "Char"],
  ["std/char/z", "Char"],
  ["std/char/0", "Char"],
  ["std/char/1", "Char"],
  ["std/char/2", "Char"],
  ["std/char/3", "Char"],
  ["std/char/4", "Char"],
  ["std/char/5", "Char"],
  ["std/char/6", "Char"],
  ["std/char/7", "Char"],
  ["std/char/8", "Char"],
  ["std/char/9", "Char"],
  ["std/char/empty", "Char"],
  ["std/char/double-quote", "Char"],
  ["std/char/single-quote", "Char"],
  ["std/char/new-line", "Char"],
  ["std/char/space", "Char"],
  ["std/char/tab", "Char"],
  ["std/char/comma", "Char"],
  ["std/char/dot", "Char"],
  ["std/char/semi-colon", "Char"],
  ["std/char/colon", "Char"],
  ["std/char/dash", "Char"],
  ["std/char/lower-dash", "Char"],
  ["std/char/left-brace", "Char"],
  ["std/char/right-brace", "Char"],
  ["std/char/curly-left-brace", "Char"],
  ["std/char/curly-right-brace", "Char"],
  ["std/char/left-bracket", "Char"],
  ["std/char/right-bracket", "Char"],
  ["std/char/pipe", "Char"],
  ["std/char/hash", "Char"],
  ["std/char/question-mark", "Char"],
  ["std/char/exclamation-mark", "Char"],
  ["std/char/minus", "Char"],
  ["std/char/plus", "Char"],
  ["std/char/equal", "Char"],
  ["std/char/asterix", "Char"],
  ["std/char/ampersand", "Char"],
  ["std/char/at", "Char"],
  ["std/char/backtick", "Char"],
  ["nl", "Char"],
  ["sp", "Char"],
  ["ep", "Char"],
  ["dq", "Char"],
  ["sq", "Char"],
  ["bt", "Char"],
  ["box", "T14 -> [T14]"],
  ["set", "[T20] -> T20 -> ()"],
  ["=!", "[T20] -> T20 -> ()"],
  ["boole-set", "[Bool] -> Bool -> ()"],
  ["boole-eqv", "[Bool] -> [Bool] -> Bool"],
  ["boolean/set", "[Bool] -> Bool -> ()"],
  ["true?", "[Bool] -> Bool"],
  ["false?", "[Bool] -> Bool"],
  ["+=", "[Int] -> Int -> ()"],
  ["-=", "[Int] -> Int -> ()"],
  ["*=", "[Int] -> Int -> ()"],
  ["/=", "[Int] -> Int -> ()"],
  ["++", "[Int] -> ()"],
  ["--", "[Int] -> ()"],
  ["**", "[Int] -> ()"],
  ["+=.", "[Float] -> Float -> ()"],
  ["-=.", "[Float] -> Float -> ()"],
  ["*=.", "[Float] -> Float -> ()"],
  ["/=.", "[Float] -> Float -> ()"],
  ["++.", "[Float] -> ()"],
  ["--.", "[Float] -> ()"],
  ["**.", "[Float] -> ()"],
  ["Bool->Int", "Bool -> Int"],
  ["Bool->Char", "Bool -> Char"],
  ["Char->Int", "Char -> Int"],
  ["Char->Bool", "Char -> Bool"],
  ["Int->Bool", "Int -> Bool"],
  ["Int->Char", "Int -> Char"],
  ["std/char/digit?", "Char -> Bool"],
  ["std/char/upper", "Char -> Char"],
  ["std/char/lower", "Char -> Char"],
  ["std/vector/length", "[T15] -> Int"],
  ["std/vector/flat/length", "[[T62]] -> Int"],
  ["std/vector/get", "[T16] -> Int -> T16"],
  ["std/vector/get/default", "[T18] -> Int -> T18 -> T18"],
  ["std/vector/2d/length", "[T16] -> Int"],
  ["std/vector/2d/get", "[T17] -> Int -> T17"],
  ["std/vector/2d/get/default", "[T19] -> Int -> T19 -> T19"],
  ["std/vector/pop!", "[T15] -> ()"],
  ["std/vector/set!", "[T17] -> Int -> T17 -> ()"],
  ["std/vector/swap!", "[T24] -> Int -> Int -> ()"],
  ["std/vector/push!", "[T21] -> T21 -> [T21]"],
  ["std/vector/pop-and-get!", "[T19] -> T19"],
  ["std/vector/push-and-get!", "[T21] -> T21 -> T21"],
  ["std/vector/update!", "[T17] -> Int -> T17 -> [T17]"],
  ["std/vector/tail!", "[T17] -> [T17]"],
  ["std/vector/append!", "[T24] -> T24 -> [T24]"],
  ["std/vector/at", "[T18] -> Int -> T18"],
  ["std/vector/first", "[T15] -> T15"],
  ["std/vector/second", "[T15] -> T15"],
  ["std/vector/third", "[T15] -> T15"],
  ["std/vector/last", "[T16] -> T16"],
  ["std/float/safe?", "Float -> Bool"],
  ["std/float/get-safe", "[Float] -> Float"],
  ["int", "Int -> [Int]"],
  ["float", "Float -> [Float]"],
  ["std/int/safe?", "Int -> Bool"],
  ["std/int/get-safe", "[Int] -> Int"],
  ["std/float/floor", "Float -> Float"],
  ["std/float/ceil", "Float -> Float"],
  ["std/fn/apply/0", "(() -> T15) -> T15"],
  ["std/fn/apply/1", "T17 -> (T17 -> T16) -> T16"],
  ["std/fn/apply/2", "T20 -> T19 -> (T20 -> T19 -> T18) -> T18"],
  ["std/fn/apply/3", "T21 -> T23 -> T22 -> (T21 -> T23 -> T22 -> T20) -> T20"],
  [
    "std/fn/apply/4",
    "T22 -> T24 -> T23 -> T26 -> (T22 -> T24 -> T23 -> T26 -> T25) -> T25",
  ],
  [
    "std/fn/apply/5",
    "T27 -> T26 -> T28 -> T29 -> T25 -> (T27 -> T26 -> T28 -> T29 -> T25 -> T24) -> T24",
  ],
  [
    "std/fn/apply/6",
    "T32 -> T28 -> T27 -> T29 -> T30 -> T31 -> (T32 -> T28 -> T27 -> T29 -> T30 -> T31 -> T26) -> T26",
  ],
  ["std/fn/apply/first/0", "(() -> T15) -> T15"],
  ["std/fn/apply/first/1", "(T17 -> T16) -> T17 -> T16"],
  ["std/fn/apply/first/2", "(T18 -> T20 -> T19) -> T18 -> T20 -> T19"],
  [
    "std/fn/apply/first/3",
    "(T23 -> T22 -> T20 -> T21) -> T23 -> T22 -> T20 -> T21",
  ],
  [
    "std/fn/apply/first/4",
    "(T24 -> T26 -> T22 -> T23 -> T25) -> T24 -> T26 -> T22 -> T23 -> T25",
  ],
  [
    "std/fn/apply/first/5",
    "(T26 -> T27 -> T25 -> T28 -> T24 -> T29) -> T26 -> T27 -> T25 -> T28 -> T24 -> T29",
  ],
  [
    "std/fn/apply/first/6",
    "(T30 -> T29 -> T27 -> T32 -> T31 -> T28 -> T26) -> T30 -> T29 -> T27 -> T32 -> T31 -> T28 -> T26",
  ],
  [
    "std/fn/apply/first/7",
    "(T32 -> T33 -> T28 -> T30 -> T31 -> T29 -> T34 -> T35) -> T32 -> T33 -> T28 -> T30 -> T31 -> T29 -> T34 -> T35",
  ],
  [
    "std/fn/apply/first/8",
    "(T31 -> T36 -> T33 -> T30 -> T32 -> T38 -> T34 -> T37 -> T35) -> T31 -> T36 -> T33 -> T30 -> T32 -> T38 -> T34 -> T37 -> T35",
  ],
  [
    "std/fn/apply/first/9",
    "(T41 -> T37 -> T40 -> T36 -> T33 -> T38 -> T34 -> T39 -> T35 -> T32) -> T41 -> T37 -> T40 -> T36 -> T33 -> T38 -> T34 -> T39 -> T35 -> T32",
  ],
  [
    "std/fn/apply/first/10",
    "(T38 -> T37 -> T42 -> T41 -> T36 -> T43 -> T40 -> T44 -> T35 -> T39 -> T34) -> T38 -> T37 -> T42 -> T41 -> T36 -> T43 -> T40 -> T44 -> T35 -> T39 -> T34",
  ],
  ["std/fn/combinator/1", "(T17 -> T16) -> T17 -> T16"],
  ["std/fn/combinator/2", "(T18 -> T20) -> (T19 -> T18) -> T19 -> T20"],
  [
    "std/fn/combinator/3",
    "(T21 -> T22) -> (T23 -> T21) -> (T20 -> T23) -> T20 -> T22",
  ],
  [
    "std/fn/combinator/4",
    "(T23 -> T24) -> (T26 -> T23) -> (T25 -> T26) -> (T22 -> T25) -> T22 -> T24",
  ],
  [
    "std/fn/combinator/5",
    "(T27 -> T28) -> (T24 -> T27) -> (T25 -> T24) -> (T29 -> T25) -> (T26 -> T29) -> T26 -> T28",
  ],
  [
    "std/fn/combinator/6",
    "(T26 -> T28) -> (T29 -> T26) -> (T30 -> T29) -> (T32 -> T30) -> (T31 -> T32) -> (T27 -> T31) -> T27 -> T28",
  ],
  [
    "std/fn/combinator/7",
    "(T29 -> T33) -> (T34 -> T29) -> (T30 -> T34) -> (T32 -> T30) -> (T31 -> T32) -> (T35 -> T31) -> (T28 -> T35) -> T28 -> T33",
  ],
  [
    "std/fn/combinator/8",
    "(T35 -> T31) -> (T36 -> T35) -> (T33 -> T36) -> (T30 -> T33) -> (T34 -> T30) -> (T37 -> T34) -> (T32 -> T37) -> (T38 -> T32) -> T38 -> T31",
  ],
  [
    "std/fn/combinator/9",
    "(T37 -> T33) -> (T35 -> T37) -> (T39 -> T35) -> (T36 -> T39) -> (T38 -> T36) -> (T34 -> T38) -> (T40 -> T34) -> (T41 -> T40) -> (T32 -> T41) -> T32 -> T33",
  ],
  ["std/fn/rev/combinator/1", "(T16 -> T17) -> T16 -> T17"],
  ["std/fn/rev/combinator/2", "(T18 -> T20) -> (T20 -> T19) -> T18 -> T19"],
  [
    "std/fn/rev/combinator/3",
    "(T22 -> T21) -> (T21 -> T20) -> (T20 -> T23) -> T22 -> T23",
  ],
  [
    "std/fn/rev/combinator/4",
    "(T24 -> T22) -> (T22 -> T25) -> (T25 -> T26) -> (T26 -> T23) -> T24 -> T23",
  ],
  [
    "std/fn/rev/combinator/5",
    "(T24 -> T29) -> (T29 -> T26) -> (T26 -> T27) -> (T27 -> T25) -> (T25 -> T28) -> T24 -> T28",
  ],
  [
    "std/fn/rev/combinator/6",
    "(T30 -> T28) -> (T28 -> T31) -> (T31 -> T29) -> (T29 -> T26) -> (T26 -> T27) -> (T27 -> T32) -> T30 -> T32",
  ],
  [
    "std/fn/rev/combinator/7",
    "(T33 -> T30) -> (T30 -> T31) -> (T31 -> T32) -> (T32 -> T28) -> (T28 -> T34) -> (T34 -> T29) -> (T29 -> T35) -> T33 -> T35",
  ],
  [
    "std/fn/rev/combinator/8",
    "(T33 -> T38) -> (T38 -> T35) -> (T35 -> T31) -> (T31 -> T30) -> (T30 -> T37) -> (T37 -> T34) -> (T34 -> T36) -> (T36 -> T32) -> T33 -> T32",
  ],
  [
    "std/fn/rev/combinator/9",
    "(T33 -> T36) -> (T36 -> T38) -> (T38 -> T37) -> (T37 -> T41) -> (T41 -> T35) -> (T35 -> T39) -> (T39 -> T32) -> (T32 -> T34) -> (T34 -> T40) -> T33 -> T40",
  ],
  ["std/fn/combinator/i", "T14 -> T14"],
  ["std/fn/combinator/k", "T16 -> T15 -> T16"],
  ["std/fn/combinator/ki", "T15 -> T16 -> T16"],
  ["std/fn/combinator/w", "(T18 -> T18 -> T17) -> T18 -> T17"],
  ["std/fn/combinator/b", "(T20 -> T19) -> (T18 -> T20) -> T18 -> T19"],
  ["std/fn/combinator/c", "(T18 -> T19 -> T20) -> T19 -> T18 -> T20"],
  ["std/fn/combinator/s", "(T21 -> T20 -> T19) -> (T21 -> T20) -> T21 -> T19"],
  [
    "std/fn/combinator/d",
    "(T21 -> T22 -> T20) -> (T23 -> T22) -> T21 -> T23 -> T20",
  ],
  [
    "std/fn/combinator/b1",
    "(T20 -> T21) -> (T22 -> T23 -> T20) -> T22 -> T23 -> T21",
  ],
  [
    "std/fn/combinator/psi",
    "(T22 -> T22 -> T23) -> (T21 -> T22) -> T21 -> T21 -> T23",
  ],
  [
    "std/fn/combinator/phi",
    "(T24 -> T23) -> (T23 -> T21 -> T22) -> (T24 -> T21) -> T24 -> T22",
  ],
  ["I/comb", "T15 -> T15"],
  ["K/comb", "T17 -> T18 -> T17"],
  ["KI/comb", "T18 -> T17 -> T17"],
  ["W/comb", "(T19 -> T19 -> T20) -> T19 -> T20"],
  ["B/comb", "(T22 -> T21) -> (T23 -> T22) -> T23 -> T21"],
  ["C/comb", "(T23 -> T22 -> T21) -> T22 -> T23 -> T21"],
  ["S/comb", "(T22 -> T23 -> T24) -> (T22 -> T23) -> T22 -> T24"],
  ["D/comb", "(T27 -> T25 -> T26) -> (T24 -> T25) -> T27 -> T24 -> T26"],
  ["B1/comb", "(T24 -> T25) -> (T27 -> T26 -> T24) -> T27 -> T26 -> T25"],
  ["PSI/comb", "(T24 -> T24 -> T25) -> (T26 -> T24) -> T26 -> T26 -> T25"],
  [
    "PHI/comb",
    "(T28 -> T26) -> (T26 -> T27 -> T25) -> (T28 -> T27) -> T28 -> T25",
  ],
  ["std/fn/const", "T16 -> T15 -> T16"],
  ["std/fn/return", "Int"],
  ["std/fn/push", "Int"],
  ["std/fn/none", "Int"],
  ["std/fn/rec", "T53 -> (T53 -> {Int * [T53]}) -> [T53]"],
  ["Rec/return", "Int"],
  ["Rec/push", "Int"],
  ["Rec/none", "Int"],
  ["Rec", "T54 -> (T54 -> {Int * [T54]}) -> [T54]"],
  ["std/vector/empty?", "[T15] -> Bool"],
  ["std/vector/empty!", "[T23] -> [T23]"],
  ["std/vector/not-empty?", "[T15] -> Bool"],
  ["std/vector/in-bounds?", "[T16] -> Int -> Bool"],
  ["std/vector/for", "[T21] -> (T21 -> T20) -> ()"],
  ["std/vector/for/i", "[T21] -> (T21 -> Int -> T22) -> ()"],
  ["std/vector/filter", "[T32] -> (T32 -> Bool) -> [T32]"],
  ["std/vector/filter/i", "[T33] -> (T33 -> Int -> Bool) -> [T33]"],
  ["std/vector/reduce", "[T30] -> (T29 -> T30 -> T29) -> T29 -> T29"],
  ["std/vector/reduce/i", "[T31] -> (T30 -> T31 -> Int -> T30) -> T30 -> T30"],
  ["std/vector/map", "[T32] -> (T32 -> T31) -> [T31]"],
  ["std/vector/map/i", "[T32] -> (T32 -> Int -> T33) -> [T33]"],
  [
    "std/vector/reduce/until",
    "[T52] -> (T53 -> T52 -> T53) -> (T53 -> Bool) -> T53 -> T53",
  ],
  [
    "std/vector/reduce/until/i",
    "[T51] -> (T52 -> T51 -> Int -> T52) -> (T52 -> T51 -> Int -> Bool) -> T52 -> T52",
  ],
  ["std/vector/for/until", "[T44] -> (T44 -> T43) -> (T44 -> Bool) -> ()"],
  [
    "std/vector/for/until/i",
    "[T45] -> (T45 -> Int -> T46) -> (T45 -> Int -> Bool) -> ()",
  ],
  ["std/vector/map/until", "[T49] -> (T49 -> T50) -> (T49 -> Bool) -> [T50]"],
  [
    "std/vector/map/until/i",
    "[T52] -> (T52 -> Int -> T51) -> (T52 -> Int -> Bool) -> [T51]",
  ],
  ["std/vector/int/range", "Int -> Int -> [Int]"],
  ["std/vector/float/range", "Int -> Int -> [Float]"],
  ["std/vector/float/ones", "Int -> [Float]"],
  ["std/vector/float/zeroes", "Int -> [Float]"],
  ["std/vector/int/ones", "Int -> [Int]"],
  ["std/vector/int/zeroes", "Int -> [Int]"],
  ["std/vector/3d/int/range", "Int -> Int -> Int -> [[Int]]"],
  ["std/vector/2d/int/range", "Int -> Int -> [Int]"],
  ["std/vector/2d/float/range", "Int -> Int -> [Float]"],
  ["std/vector/char/blanks", "Int -> [Char]"],
  ["std/vector/int/all-equal?", "[Int] -> Bool"],
  ["std/vector/float/all-equal?", "[Float] -> Bool"],
  ["std/vector/char/all-equal?", "[Char] -> Bool"],
  ["std/vector/bool/all-equal?", "[Bool] -> Bool"],
  ["all-equal/int?", "[Int] -> Bool"],
  ["all-equal/float?", "[Float] -> Bool"],
  ["all-equal/char?", "[Char] -> Bool"],
  ["all-equal/bool?", "[Bool] -> Bool"],
  ["std/vector/count-of", "[T36] -> (T36 -> Bool) -> Int"],
  ["std/vector/int/count", "[Int] -> Int -> Int"],
  ["std/vector/float/count", "[Float] -> Float -> Int"],
  ["std/vector/char/count", "[Char] -> Char -> Int"],
  ["std/vector/bool/count", "[Bool] -> Bool -> Int"],
  ["std/vector/2d/count-of", "[T37] -> (T37 -> Bool) -> Int"],
  ["std/vector/2d/int/count", "[Int] -> Int -> Int"],
  ["std/vector/2d/char/count", "[Char] -> Char -> Int"],
  ["std/vector/2d/bool/count", "[Bool] -> Bool -> Int"],
  ["std/vector/3d/count-of", "[[T72]] -> (T72 -> Bool) -> Int"],
  ["std/vector/3d/int/count", "[[Int]] -> Int -> Int"],
  ["std/vector/3d/char/count", "[[Char]] -> Char -> Int"],
  ["std/vector/3d/bool/count", "[[Bool]] -> Bool -> Int"],
  ["std/vector/cons", "[T36] -> [T36] -> [T36]"],
  ["std/vector/cons!", "[T29] -> [T29] -> [T29]"],
  ["std/vector/concat", "[[T53]] -> [T53]"],
  ["std/vector/concat!", "[T46] -> [[T46]] -> [T46]"],
  ["std/vector/every?", "[T28] -> (T28 -> Bool) -> Bool"],
  ["std/vector/some?", "[T28] -> (T28 -> Bool) -> Bool"],
  ["std/vector/every/i?", "[T30] -> (T30 -> Int -> Bool) -> Bool"],
  ["std/vector/some/i?", "[T30] -> (T30 -> Int -> Bool) -> Bool"],
  ["std/vector/cartesian-product", "[T72] -> [T71] -> [{T72 * T71}]"],
  ["std/int/gcd", "Int -> Int -> Int"],
  ["std/int/lcm", "Int -> Int -> Int"],
  ["std/int/bit/set?", "Int -> Int -> Bool"],
  ["std/int/bit/set", "Int -> Int -> Int"],
  ["std/int/bit/clear", "Int -> Int -> Int"],
  ["std/int/bit/power-of-two", "Int -> Int"],
  ["std/int/bit/odd?", "Int -> Bool"],
  ["std/int/bit/even?", "Int -> Bool"],
  ["std/int/bit/average", "Int -> Int -> Int"],
  ["std/int/bit/flag-flip", "Int -> Int"],
  ["std/int/bit/toggle", "Int -> Int -> Int -> Int"],
  ["std/int/bit/same-sign?", "Int -> Int -> Bool"],
  ["std/int/bit/max", "Int -> Int -> Int"],
  ["std/int/bit/min", "Int -> Int -> Int"],
  ["std/int/bit/equal?", "Int -> Int -> Bool"],
  ["std/int/bit/modulo", "Int -> Int -> Int"],
  ["std/int/bit/n-one?", "Int -> Int -> Bool"],
  ["std/int/bit/largest-power", "Int -> Int"],
  ["std/int/abs", "Int -> Int"],
  ["std/float/abs", "Float -> Float"],
  ["std/int/positive?", "Int -> Bool"],
  ["std/int/negative?", "Int -> Bool"],
  ["std/int/invert", "Int -> Int"],
  ["std/int/zero?", "Int -> Bool"],
  ["std/int/one?", "Int -> Bool"],
  ["std/int/negative-one?", "Int -> Bool"],
  ["std/int/divisible?", "Int -> Int -> Bool"],
  ["std/int/floor/div", "Int -> Int -> Int"],
  ["std/int/ceil/div", "Int -> Int -> Int"],
  ["std/float/positive?", "Float -> Bool"],
  ["std/float/negative?", "Float -> Bool"],
  ["std/float/invert", "Float -> Float"],
  ["std/float/zero?", "Float -> Bool"],
  ["std/float/one?", "Float -> Bool"],
  ["std/float/negative-one?", "Float -> Bool"],
  ["std/float/divisible?", "Float -> Float -> Bool"],
  ["std/int/square", "Int -> Int"],
  ["std/int/even?", "Int -> Bool"],
  ["std/int/odd?", "Int -> Bool"],
  ["std/float/even?", "Float -> Bool"],
  ["std/float/odd?", "Float -> Bool"],
  ["std/vector/int/sum", "[Int] -> Int"],
  ["std/vector/float/sum", "[Float] -> Float"],
  ["std/vector/int/product", "[Int] -> Int"],
  ["std/vector/float/product", "[Float] -> Float"],
  ["std/int/mul", "Int -> Int -> Int"],
  ["std/int/add", "Int -> Int -> Int"],
  ["std/int/div", "Int -> Int -> Int"],
  ["std/int/sub", "Int -> Int -> Int"],
  ["std/int/euclidean-mod", "Int -> Int -> Int"],
  ["std/int/euclidean-distance", "Int -> Int -> Int -> Int -> Int"],
  ["std/int/manhattan-distance", "Int -> Int -> Int -> Int -> Int"],
  ["std/int/chebyshev-distance", "Int -> Int -> Int -> Int -> Int"],
  ["std/int/max", "Int -> Int -> Int"],
  ["std/int/min", "Int -> Int -> Int"],
  ["std/float/max", "Float -> Float -> Float"],
  ["std/float/min", "Float -> Float -> Float"],
  ["std/vector/int/maximum", "[Int] -> Int"],
  ["std/vector/int/minimum", "[Int] -> Int"],
  ["std/vector/float/maximum", "[Float] -> Float"],
  ["std/vector/float/minimum", "[Float] -> Float"],
  ["std/float/average", "Float -> Float -> Float"],
  ["std/int/average", "Int -> Int -> Int"],
  ["std/vector/int/mean", "[Int] -> Int"],
  ["std/vector/float/mean", "[Float] -> Float"],
  ["std/vector/int/median", "[Int] -> Int"],
  ["std/vector/float/median", "[Float] -> Float"],
  ["std/int/normalize", "Int -> Int -> Int -> Int"],
  ["std/int/linear-interpolation", "Int -> Int -> Int -> Int"],
  ["std/int/gauss-sum", "Int -> Int"],
  ["std/int/gauss-sum-sequance", "Int -> Int -> Int"],
  ["std/int/clamp", "Int -> Int -> Int"],
  ["std/int/clamp-range", "Int -> Int -> Int -> Int"],
  ["std/int/between?", "Int -> Int -> Int -> Bool"],
  ["std/int/overlap?", "Int -> Int -> Int -> Bool"],
  ["std/float/clamp", "Float -> Float -> Float"],
  ["std/float/clamp-range", "Float -> Float -> Float -> Float"],
  ["std/float/between?", "Float -> Float -> Float -> Bool"],
  ["std/float/overlap?", "Float -> Float -> Float -> Bool"],
  ["std/int/sqrt", "Int -> Int"],
  ["std/int/expt", "Int -> Int -> Int"],
  ["iexpt", "Int -> Int -> Int"],
  ["std/float/sqrt", "Float -> Float"],
  ["std/float/expt", "Float -> Float -> Float"],
  ["std/int/delta", "Int -> Int -> Int"],
  ["std/float/delta", "Float -> Float -> Float"],
  ["std/vector/map/adjacent", "[T36] -> (T36 -> T36 -> T37) -> [T37]"],
  ["std/vector/2d/int/set!", "[T21] -> [T21] -> ()"],
  ["std/vector/2d/int/add", "[Int] -> [Int] -> [Int]"],
  ["std/vector/2d/int/sub", "[Int] -> [Int] -> [Int]"],
  ["std/vector/2d/int/mul", "[Int] -> [Int] -> [Int]"],
  ["std/vector/2d/int/div", "[Int] -> [Int] -> [Int]"],
  ["std/vector/2d/int/mag/sqrt", "[Int] -> Int"],
  ["std/vector/2d/int/mag", "[Int] -> Int"],
  ["std/vector/2d/int/dot", "[Int] -> [Int] -> Int"],
  ["std/vector/2d/int/cross", "[Int] -> [Int] -> [Int]"],
  ["std/vector/2d/int/dist", "[Int] -> [Int] -> Int"],
  ["std/vector/2d/int/normalize", "[Int] -> [Int]"],
  ["std/vector/2d/int/limit", "[Int] -> Int -> [Int]"],
  ["std/vector/2d/int/add!", "[Int] -> [Int] -> ()"],
  ["std/vector/2d/int/sub!", "[Int] -> [Int] -> ()"],
  ["std/vector/2d/int/mul!", "[Int] -> [Int] -> ()"],
  ["std/vector/2d/int/div!", "[Int] -> [Int] -> ()"],
  ["std/vector/2d/int/normalize!", "[Int] -> ()"],
  ["std/vector/2d/int/limit!", "[Int] -> Int -> ()"],
  ["std/vector/2d/int/mag!", "[Int] -> [Int] -> ()"],
  ["std/vector/3d/int/set!", "[T23] -> [T23] -> ()"],
  ["std/vector/3d/int/add", "[Int] -> [Int] -> [Int]"],
  ["std/vector/3d/int/sub", "[Int] -> [Int] -> [Int]"],
  ["std/vector/3d/int/mul", "[Int] -> [Int] -> [Int]"],
  ["std/vector/3d/int/div", "[Int] -> [Int] -> [Int]"],
  ["std/vector/3d/int/mag/sqrt", "[Int] -> Int"],
  ["std/vector/3d/int/mag", "[Int] -> Int"],
  ["std/vector/3d/int/dot", "[Int] -> [Int] -> Int"],
  ["std/vector/3d/int/cross", "[Int] -> [Int] -> [Int]"],
  ["std/vector/3d/int/dist", "[Int] -> [Int] -> Int"],
  ["std/vector/3d/int/normalize", "[Int] -> [Int]"],
  ["std/vector/3d/int/limit", "[Int] -> Int -> [Int]"],
  ["std/vector/3d/int/add!", "[Int] -> [Int] -> ()"],
  ["std/vector/3d/int/sub!", "[Int] -> [Int] -> ()"],
  ["std/vector/3d/int/mul!", "[Int] -> [Int] -> ()"],
  ["std/vector/3d/int/div!", "[Int] -> [Int] -> ()"],
  ["std/vector/3d/int/normalize!", "[Int] -> ()"],
  ["std/vector/3d/int/limit!", "[Int] -> Int -> ()"],
  ["std/vector/3d/int/mag!", "[Int] -> [Int] -> ()"],
  ["std/vector/zipper", "[T28] -> [T28] -> [[T28]]"],
  ["std/vector/zip", "[[T36]] -> [[T36]]"],
  ["std/vector/unzip", "[[T42]] -> [[T42]]"],
  ["std/vector/tuple/zipper", "[T28] -> [T29] -> [{T28 * T29}]"],
  ["std/vector/tuple/zip", "{[T35] * [T36]} -> [{T35 * T36}]"],
  ["std/vector/tuple/unzip", "[{T42 * T43}] -> {[T42] * [T43]}"],
  [
    "std/vector/tuple/zip-with",
    "[T28] -> [T27] -> (T28 -> T27 -> T26) -> [T26]",
  ],
  ["std/vector/rest", "[T29] -> Int -> [T29]"],
  ["std/vector/slice", "[T29] -> Int -> Int -> [T29]"],
  ["std/vector/drop", "[T29] -> Int -> [T29]"],
  ["std/vector/drop/last", "[T29] -> Int -> [T29]"],
  ["std/vector/take", "[T28] -> Int -> [T28]"],
  ["std/vector/take/last", "[T30] -> Int -> [T30]"],
  ["std/vector/reverse", "[T28] -> [T28]"],
  ["std/vector/reverse!", "[T30] -> ()"],
  ["std/vector/find-index", "[T31] -> (T31 -> Bool) -> Int"],
  ["std/vector/buckets", "Int -> [[T24]]"],
  ["std/vector/char/equal?", "[Char] -> [Char] -> Bool"],
  ["std/vector/char/greater?", "[Char] -> [Char] -> Bool"],
  ["std/vector/char/lesser?", "[Char] -> [Char] -> Bool"],
  ["std/vector/char/match?", "[Char] -> [Char] -> Bool"],
  ["std/vector/char/greater-or-equal?", "[Char] -> [Char] -> Bool"],
  ["std/vector/char/lesser-or-equal?", "[Char] -> [Char] -> Bool"],
  ["std/vector/char/negative?", "[Char] -> Bool"],
  ["std/vector/partition", "[T37] -> Int -> [[T37]]"],
  [
    "std/vector/sort-partition!",
    "[T49] -> Int -> Int -> (T49 -> T49 -> Bool) -> Int",
  ],
  ["std/vector/sort!", "[T74] -> (T74 -> T74 -> Bool) -> [T74]"],
  ["std/int/hash", "[T36] -> [T35] -> Int"],
  ["std/vector/hash/set/has?", "[[[Char]]] -> [Char] -> Bool"],
  ["std/vector/hash/table/has?", "[[[[Char]]]] -> [Char] -> Bool"],
  ["std/vector/hash/set/add!", "[[[Char]]] -> [Char] -> [[[Char]]]"],
  ["std/vector/hash/set/remove!", "[[[Char]]] -> [Char] -> [[[Char]]]"],
  [
    "std/vector/hash/table/set!",
    "[[[[Char]]]] -> [Char] -> Int -> [[[[Char]]]]",
  ],
  ["std/vector/hash/table/delete!", "[[[[Char]]]] -> [Char] -> [[[[Char]]]]"],
  ["std/vector/hash/clear!", "[[T29]] -> [[T29]]"],
  ["std/vector/hash/table/get-helper", "[[[[T75]]]] -> Int -> [Char] -> [T75]"],
  ["std/vector/hash/table/get", "[[[[Char]]]] -> [Char] -> Char"],
  ["std/vector/hash/table/count", "[[Char]] -> [[[[Char]]]]"],
  [
    "std/vector/tuple/hash/table/set!",
    "[[[{[Char] * T103}]]] -> [Char] -> T103 -> [[[{[Char] * T103}]]]",
  ],
  [
    "std/vector/tuple/hash/table/has?",
    "[[[{[Char] * T112}]]] -> [Char] -> Bool",
  ],
  [
    "std/vector/tuple/hash/table/remove!",
    "[[[{[Char] * T109}]]] -> [Char] -> [[[{[Char] * T109}]]]",
  ],
  [
    "std/vector/tuple/hash/table/get-helper",
    "[[[{[Char] * T73}]]] -> Int -> [Char] -> [{[Char] * T73}]",
  ],
  [
    "std/vector/tuple/hash/table/get",
    "[[[{[Char] * T101}]]] -> [Char] -> [{[Char] * T101}]",
  ],
  ["std/vector/tuple/hash/table/count", "[[Char]] -> [[[{[Char] * Int}]]]"],
  ["std/vector/tuple/hash/table/entries", "[[[{T83 * T84}]]] -> [{T83 * T84}]"],
  ["std/vector/tuple/hash/table/keys", "[[[{T81 * T80}]]] -> [T81]"],
  ["std/vector/tuple/hash/table/values", "[[[{T81 * T80}]]] -> [T80]"],
  ["std/vector/tuple/hash/set/keys", "[[[T78]]] -> [T78]"],
  [
    "std/vector/tuple/hash/table/drop!",
    "[[[{[Char] * T116}]]] -> [[Char]] -> ()",
  ],
  [
    "std/vector/tuple/hash/table/keep",
    "[[[{[Char] * T144}]]] -> [[Char]] -> [[[{[Char] * [Char]}]]]",
  ],
  [
    "std/vector/tuple/hash/table/omit",
    "[[[{[Char] * T137}]]] -> [[Char]] -> [[[{[Char] * T137}]]]",
  ],
  [
    "std/vector/tuple/hash/table/merge!",
    "[[[{[Char] * T188}]]] -> [[[{[Char] * T188}]]] -> ()",
  ],
  [
    "std/vector/tuple/hash/table/merge",
    "[[[{[Char] * T206}]]] -> [[[{[Char] * T206}]]] -> [[[{[Char] * T206}]]]",
  ],
  ["std/vector/sliding-window", "[T73] -> Int -> [[T73]]"],
  ["std/vector/flat-one", "[[T59]] -> [T59]"],
  ["std/vector/hash/table/keys", "[[[T78]]] -> [T78]"],
  ["std/vector/hash/table/values", "[[[T78]]] -> [T78]"],
  ["std/vector/hash/table/entries", "[[T61]] -> [T61]"],
  ["std/convert/char->digit", "Char -> Int"],
  ["std/convert/chars->digits", "[Char] -> [Int]"],
  ["std/convert/digit->char", "Int -> Char"],
  ["std/convert/digits->chars", "[Int] -> [Char]"],
  ["std/convert/bool->int", "Bool -> Int"],
  ["std/convert/int->bool", "Int -> Bool"],
  ["std/convert/vector->string", "[[Char]] -> Char -> [Char]"],
  ["std/convert/string->vector", "[Char] -> Char -> [[Char]]"],
  ["std/convert/positive-or-negative-digits->integer", "[Int] -> Int"],
  ["std/convert/chars->positive-or-negative-digits", "[Char] -> [Int]"],
  ["std/convert/digits->integer", "[Int] -> Int"],
  ["std/convert/positive-or-negative-chars->integer", "[Char] -> Int"],
  ["std/convert/chars->integer", "[Char] -> Int"],
  ["std/convert/chars->digits/float", "[Char] -> [[Int]]"],
  ["std/convert/chars->ufloat", "[Char] -> Float"],
  ["std/convert/chars->float", "[Char] -> Float"],
  ["std/convert/int->char/alphabet", "Int -> Char -> Char"],
  ["std/vector/unique-pairs", "[T42] -> [[T42]]"],
  ["std/vector/tuple/unique-pairs", "[T42] -> [{T42 * T42}]"],
  ["std/vector/int/unique", "[Int] -> [Int]"],
  ["std/vector/char/unique", "[Char] -> [Char]"],
  ["std/vector/3d/dimensions", "[[T17]] -> [Int]"],
  ["std/vector/3d/in-bounds?", "[[T22]] -> Int -> Int -> Bool"],
  ["std/vector/3d/set!", "[[T19]] -> Int -> Int -> T19 -> Int"],
  ["std/vector/3d/diagonal-neighborhood", "[[Int]]"],
  ["std/vector/3d/kernel-neighborhood", "[[Int]]"],
  ["std/vector/3d/moore-neighborhood", "[[Int]]"],
  ["std/vector/3d/von-neumann-neighborhood", "[[Int]]"],
  [
    "std/vector/3d/adjacent",
    "[[T52]] -> [[Int]] -> Int -> Int -> (T52 -> [Int] -> Int -> Int -> ()) -> ()",
  ],
  [
    "std/vector/3d/sliding-adjacent-sum",
    "[[T51]] -> [[Int]] -> Int -> Int -> Int -> (Int -> T51 -> Int) -> Int",
  ],
  [
    "std/vector/tuple/hash/table/group-by",
    "[T188] -> (T188 -> [Char]) -> [[[{[Char] * [T188]}]]]",
  ],
  ["std/node/parent", "Int -> Int"],
  ["std/node/left", "Int -> Int"],
  ["std/node/right", "Int -> Int"],
  ["std/heap/top", "Int"],
  ["std/heap/greater?", "[T21] -> Int -> Int -> (T21 -> T21 -> Bool) -> Bool"],
  ["std/heap/sift-up!", "[T64] -> (T64 -> T64 -> Bool) -> [T64]"],
  ["std/heap/sift-down!", "[T80] -> (T80 -> T80 -> Bool) -> [T80]"],
  ["std/heap/peek", "[T15] -> T15"],
  ["std/heap/push!", "[T72] -> T72 -> (T72 -> T72 -> Bool) -> ()"],
  ["std/heap/pop!", "[T88] -> (T88 -> T88 -> Bool) -> ()"],
  ["std/heap/replace!", "[T85] -> T85 -> (T85 -> T85 -> Bool) -> [T85]"],
  ["std/heap/empty?", "[T16] -> Bool"],
  ["std/heap/not-empty?", "[T16] -> Bool"],
  ["std/heap/empty!", "[T24] -> [T24]"],
  ["std/convert/vector->heap", "[T92] -> (T92 -> T92 -> Bool) -> [T92]"],
  ["std/convert/set->vector", "[[[T78]]] -> [[T78]]"],
  ["std/vector/hash/set/max-capacity", "[T33] -> [T31] -> [[T32]]"],
  ["std/vector/hash/set/min-capacity", "[T31] -> [T32] -> [[T33]]"],
  ["std/convert/integer->string-base", "Int -> Int -> [Char]"],
  ["std/convert/integer->string", "Int -> [Char]"],
  ["std/convert/vector->set", "[[Char]] -> [[[Char]]]"],
  [
    "std/vector/hash/set/intersection",
    "[[[Char]]] -> [[[Char]]] -> [[[Char]]]",
  ],
  ["std/vector/hash/set/difference", "[[[Char]]] -> [[[Char]]] -> [[[Char]]]"],
  ["std/vector/hash/set/xor", "[[[Char]]] -> [[[Char]]] -> [[[Char]]]"],
  ["std/vector/hash/set/union", "[[[Char]]] -> [[[Char]]] -> [[[Char]]]"],
  ["std/integer/decimal-scaling", "Int"],
  ["std/float/decimal-scaling", "Float"],
  ["std/convert/float->string", "Float -> [Char]"],
  ["std/vector/deque/new", "T15 -> [[T15]]"],
  ["std/vector/deque/offset-left", "[[T16]] -> Int"],
  ["std/vector/deque/offset-right", "[[T16]] -> Int"],
  ["std/vector/deque/length", "[[T18]] -> Int"],
  ["std/vector/deque/empty?", "[[T20]] -> Bool"],
  ["std/vector/deque/empty!", "[[T19]] -> [[T19]]"],
  ["std/vector/deque/get", "[[T23]] -> Int -> T23"],
  ["std/vector/deque/set!", "[[T24]] -> Int -> T24 -> [[T24]]"],
  ["std/vector/deque/add-to-left!", "[[T18]] -> T18 -> ()"],
  ["std/vector/deque/add-to-right!", "[[T18]] -> T18 -> ()"],
  ["std/vector/deque/remove-from-left!", "[[T31]] -> [[T31]]"],
  ["std/vector/deque/remove-from-right!", "[[T31]] -> [[T31]]"],
  ["std/vector/deque/iter", "[[T54]] -> (T54 -> T53) -> Int"],
  ["std/vector/deque/map", "[[T83]] -> (T83 -> T82) -> [[T82]]"],
  ["std/vector/deque/balance?", "[[T22]] -> Bool"],
  ["std/convert/vector->deque", "[T66] -> [[T66]]"],
  ["std/convert/deque->vector", "[[T59]] -> [T59]"],
  ["std/vector/deque/balance!", "[[T125]] -> [[T125]]"],
  ["std/vector/deque/append!", "[[T21]] -> T21 -> [[T21]]"],
  ["std/vector/deque/prepend!", "[[T21]] -> T21 -> [[T21]]"],
  ["std/vector/deque/head!", "[[T136]] -> [[T136]]"],
  ["std/vector/deque/tail!", "[[T136]] -> [[T136]]"],
  ["std/vector/deque/first", "[[T25]] -> T25"],
  ["std/vector/deque/last", "[[T31]] -> T31"],
  ["std/vector/deque/pop-right!", "[[T146]] -> T146"],
  ["std/vector/deque/pop-left!", "[[T144]] -> T144"],
  ["std/vector/deque/rotate-left!", "[[T161]] -> Int -> [[T161]]"],
  ["std/vector/deque/rotate-right!", "[[T162]] -> Int -> [[T162]]"],
  ["std/vector/deque/slice", "[[T106]] -> Int -> Int -> [[T106]]"],
  ["std/vector/queue/new", "T16 -> [[T16]]"],
  ["std/vector/stack/new", "T16 -> [[T16]]"],
  ["std/vector/queue/empty?", "[[T21]] -> Bool"],
  ["std/vector/queue/not-empty?", "[[T22]] -> Bool"],
  ["std/vector/queue/empty!", "[[T20]] -> [[T20]]"],
  ["std/vector/queue/enqueue!", "[[T24]] -> T24 -> [[T24]]"],
  ["std/vector/queue/dequeue!", "[[T138]] -> [[T138]]"],
  ["std/vector/queue/peek", "[[T27]] -> T27"],
  ["std/vector/stack/empty?", "[[T21]] -> Bool"],
  ["std/vector/stack/not-empty?", "[[T22]] -> Bool"],
  ["std/vector/stack/empty!", "[[T20]] -> [[T20]]"],
  ["std/vector/stack/push!", "[[T24]] -> T24 -> [[T24]]"],
  ["std/vector/stack/pop!", "[[T138]] -> [[T138]]"],
  ["std/vector/stack/peek", "[[T33]] -> T33"],
  ["std/vector/3d/for", "[[T28]] -> (T28 -> T27) -> [[T28]]"],
  ["std/vector/3d/for/i", "[[T29]] -> (T29 -> Int -> Int -> T30) -> [[T29]]"],
  ["std/vector/3d/points", "[[T49]] -> (T49 -> Bool) -> [[Int]]"],
  [
    "std/vector/reduce/until",
    "[T52] -> (T53 -> T52 -> T53) -> (T53 -> Bool) -> T53 -> T53",
  ],
  ["std/vector/concat/with", "[[T61]] -> T61 -> [T61]"],
  ["std/vector/char/lines", "[Char] -> [[Char]]"],
  ["std/vector/char/words", "[Char] -> [[Char]]"],
  ["std/vector/char/commas", "[Char] -> [[Char]]"],
  ["std/vector/int/pair/sub", "[Int] -> Int"],
  ["std/vector/int/pair/add", "[Int] -> Int"],
  ["std/vector/int/pair/mult", "[Int] -> Int"],
  ["std/vector/int/pair/div", "[Int] -> Int"],
  ["std/vector/sort/asc!", "[Int] -> [Int]"],
  ["std/vector/sort/desc!", "[Int] -> [Int]"],
  ["std/vector/equal?", "[Int] -> [Int] -> Bool"],
  ["std/convert/integer->bits", "Int -> [Int]"],
  ["std/vector/subset", "[T105] -> [[T105]]"],
  ["std/vector/flat-map", "[[T75]] -> (T75 -> T76) -> [T76]"],
  ["std/convert/bits->integer", "[Int] -> Int"],
  ["std/vector/copy", "[T36] -> [T36]"],
  ["std/int/reduce", "Int -> (T38 -> Int -> T38) -> T38 -> T38"],
  ["std/vector/2d/fill", "Int -> (Int -> T54) -> [T54]"],
  ["std/vector/3d/fill", "Int -> Int -> (Int -> Int -> T41) -> [[T41]]"],
  ["std/vector/3d/product", "[[Int]] -> [[Int]] -> [[Int]]"],
  ["std/vector/3d/dot-product", "[Int] -> [Int] -> Int"],
  ["std/vector/3d/rotate", "[[T44]] -> [[T44]]"],
  ["std/vector/2d/interleave", "[T34] -> [T34] -> [T34]"],
  ["std/vector/intersperse", "[T37] -> T37 -> [T37]"],
  ["std/vector/int/sequence", "[T25] -> [Int]"],
  ["std/int/shoelace", "[[Int]] -> Int"],
  ["std/int/collinear?", "[[Int]] -> Bool"],
  ["std/vector/int/big/range", "Int -> Int -> [[Int]]"],
  ["std/int/big/add", "[Int] -> [Int] -> [Int]"],
  ["std/int/big/sub", "[Int] -> [Int] -> [Int]"],
  ["std/int/big/mul", "[Int] -> [Int] -> [Int]"],
  ["std/vector/int/remove-leading-zeroes", "[Int] -> [Int]"],
  ["std/int/big/less-or-equal?", "[Int] -> [Int] -> Bool"],
  ["std/int/big/greater-or-equal?", "[Int] -> [Int] -> Bool"],
  ["std/int/big/less-than?", "[Int] -> [Int] -> Bool"],
  ["std/int/big/greater-than?", "[Int] -> [Int] -> Bool"],
  ["std/int/big/equal?", "[Int] -> [Int] -> Bool"],
  ["std/int/big/div", "[Int] -> [Int] -> [Int]"],
  ["std/int/big/square", "[Int] -> [Int]"],
  ["std/int/big/floor/div", "[Int] -> [Int] -> [Int]"],
  ["std/int/big/ceil/div", "[Int] -> [Int] -> [Int]"],
  ["std/vector/int/big/sum", "[[Int]] -> [Int]"],
  ["std/vector/int/big/product", "[[Int]] -> [Int]"],
  ["std/int/big/new", "[Char] -> [Int]"],
  ["std/int/pow/big", "Int -> Int -> [Int]"],
  ["std/int/big/pow", "[Int] -> Int -> [Int]"],
  ["std/int/big/expt", "[Int] -> [Int] -> [Int]"],
  ["std/convert/integer->digits-base", "Int -> Int -> [Int]"],
  ["std/convert/integer->digits", "Int -> [Int]"],
  ["std/vector/adjacent-difference", "[T71] -> (T71 -> T71 -> T71) -> [T71]"],
  ["std/vector/adjacent-difference!", "[T49] -> (T49 -> T49 -> T49) -> ()"],
  ["std/convert/vector/3d->string", "[[[Char]]] -> Char -> Char -> [Char]"],
  ["std/vector/cycle", "Int -> [T29] -> [T29]"],
  ["std/vector/replicate", "Int -> T27 -> [T27]"],
  ["std/vector/int/extreme", "[Int] -> {Int * Int}"],
  ["std/tuple/map", "{T21 * T23} -> (T21 -> T23 -> T22) -> T22"],
  ["std/tuple/map/fst", "{T18 * T20} -> (T18 -> T19) -> T19"],
  ["std/tuple/map/snd", "{T19 * T20} -> (T20 -> T18) -> T18"],
  ["std/tuple/swap", "{T19 * T18} -> {T18 * T19}"],
  ["get*", "[T26] -> Int -> (T26 -> T27) -> (() -> T28) -> ()"],
  ["std/vector/get*", "[T26] -> Int -> (T26 -> T27) -> (() -> T28) -> ()"],
  ["std/vector/2d/get*", "[T31] -> Int -> (T31 -> T29) -> (() -> T30) -> ()"],
  [
    "std/vector/3d/get*",
    "[[T36]] -> Int -> Int -> (T36 -> T35) -> (() -> T34) -> ()",
  ],
  [
    "std/vector/hash/table/get*",
    "[[[[Char]]]] -> [Char] -> (Char -> T137) -> (() -> T136) -> ()",
  ],
  ["std/vector/enumerate", "[T45] -> [{Int * T45}]"],
  ["std/int/factorial", "Int -> Int"],
  ["std/float/factorial", "Float -> Float"],
  ["std/vector/permutations", "[T75] -> [[T75]]"],
  ["std/vector/combinations", "[T62] -> [[T62]]"],
  ["std/vector/combinations/n", "[T60] -> Int -> [[T60]]"],
  ["std/int/div/option", "Int -> Int -> {Bool * Int}"],
  ["std/int/expt/option", "Int -> Int -> {Bool * Int}"],
  ["std/int/mod/option", "Int -> Int -> {Bool * Int}"],
  ["std/int/sqrt/option", "Int -> {Bool * Int}"],
  ["std/float/div/option", "Float -> Float -> {Bool * Float}"],
  ["std/float/expt/option", "Float -> Float -> {Bool * Float}"],
  ["std/float/mod/option", "Float -> Float -> {Bool * Float}"],
  ["std/float/sqrt/option", "Float -> {Bool * Float}"],
  ["std/true/option", "T14 -> {Bool * T14}"],
  ["std/false/option", "T14 -> {Bool * T14}"],
  [
    "std/vector/option/resolve",
    "[{Bool * T53}] -> ([T53] -> T54) -> T54 -> {Bool * T54}",
  ],
  ["std/fn/exec", "T17 -> (T17 -> T16) -> T16"],
  [
    "std/convert/vector->tuple",
    "T19 -> (T19 -> T20) -> (T19 -> T18) -> {T20 * T18}",
  ],
  ["std/tuple/int/add", "{Int * Int} -> Int"],
  ["std/tuple/int/sub", "{Int * Int} -> Int"],
  ["std/tuple/int/mul", "{Int * Int} -> Int"],
  ["std/tuple/int/div", "{Int * Int} -> Int"],
  ["loop/repeat", "Int -> (() -> T18) -> ()"],
  ["loop/some-range?", "Int -> Int -> (Int -> Bool) -> Bool"],
  ["loop/some-n?", "Int -> (Int -> Bool) -> Bool"],
  ["push!", "[T17] -> T17 -> ()"],
  ["pull!", "[T20] -> T20"],
  ["swap!", "Int -> Int -> [T28] -> ()"],
  ["scan!", "(T52 -> T52 -> T52) -> [T52] -> ()"],
  ["empty!", "[T27] -> ()"],
  ["reverse!", "[T31] -> ()"],
  ["sort!", "(T77 -> T77 -> Bool) -> [T77] -> [T77]"],
  ["emod", "Int -> Int -> Int"],
  ["mul", "Int -> Int -> Int"],
  ["div", "Int -> Int -> Int"],
  ["add", "Int -> Int -> Int"],
  ["sub", "Int -> Int -> Int"],
  ["const", "T18 -> T17 -> T18"],
  ["floor", "Float -> Float"],
  ["ceil", "Float -> Float"],
  ["extreme", "[Int] -> {Int * Int}"],
  ["map/tuple", "(T28 -> T26 -> T27) -> {T28 * T26} -> T27"],
  ["map/fst", "(T24 -> T23) -> {T24 * T25} -> T23"],
  ["map/snd", "(T23 -> T25) -> {T24 * T23} -> T25"],
  ["flat-map", "(T80 -> T79) -> [[T80]] -> [T79]"],
  ["map", "(T35 -> T36) -> [T35] -> [T36]"],
  ["for", "(T24 -> T25) -> [T24] -> ()"],
  ["for/i", "(T25 -> Int -> T26) -> [T25] -> ()"],
  ["each", "[T25] -> (T25 -> T24) -> [T25]"],
  ["each/i", "[T25] -> (T25 -> Int -> T26) -> [T25]"],
  ["filter", "(T35 -> Bool) -> [T35] -> [T35]"],
  ["reduce", "(T34 -> T35 -> T34) -> T34 -> [T35] -> T34"],
  [
    "reduce/until",
    "(T59 -> T58 -> T59) -> (T59 -> Bool) -> T59 -> [T58] -> T59",
  ],
  ["transpose", "[[T45]] -> [[T45]]"],
  ["interleave", "[T35] -> [T35] -> [T35]"],
  ["intersperse", "T40 -> [T40] -> [T40]"],
  ["every?", "(T31 -> Bool) -> [T31] -> Bool"],
  ["some?", "(T31 -> Bool) -> [T31] -> Bool"],
  ["empty?", "[T16] -> Bool"],
  ["not-empty?", "[T16] -> Bool"],
  ["exclude", "(T37 -> Bool) -> [T37] -> [T37]"],
  ["select", "(T35 -> Bool) -> [T35] -> [T35]"],
  ["find", "(T34 -> Bool) -> [T34] -> Int"],
  ["partition", "Int -> [T40] -> [[T40]]"],
  ["reverse", "[T29] -> [T29]"],
  ["slice", "Int -> Int -> [T33] -> [T33]"],
  ["cons", "[T37] -> [T37] -> [T37]"],
  ["range", "Int -> Int -> [Int]"],
  ["range/int", "Int -> Int -> [Int]"],
  ["range/float", "Int -> Int -> [Float]"],
  ["square", "Int -> Int"],
  ["expt", "Int -> Int -> Int"],
  ["sqrt", "Int -> Int"],
  ["expt/int", "Int -> Int -> Int"],
  ["sqrt/int", "Int -> Int"],
  ["expt/float", "Float -> Float -> Float"],
  ["sqrt/float", "Float -> Float"],
  ["odd?", "Int -> Bool"],
  ["even?", "Int -> Bool"],
  ["odd/int?", "Int -> Bool"],
  ["even/int?", "Int -> Bool"],
  ["odd/float?", "Float -> Bool"],
  ["even/float?", "Float -> Bool"],
  ["one?", "Int -> Bool"],
  ["zero?", "Int -> Bool"],
  ["one/int?", "Int -> Bool"],
  ["zero/int?", "Int -> Bool"],
  ["one/float?", "Float -> Bool"],
  ["zero/float?", "Float -> Bool"],
  ["map/until", "(T54 -> T55) -> (T54 -> Bool) -> [T54] -> [T55]"],
  [
    "map/until/i",
    "(T56 -> Int -> T57) -> (T56 -> Int -> Bool) -> [T56] -> [T57]",
  ],
  [
    "reduce/until",
    "(T59 -> T58 -> T59) -> (T59 -> Bool) -> T59 -> [T58] -> T59",
  ],
  [
    "reduce/until/i",
    "(T57 -> T58 -> Int -> T57) -> (T57 -> T58 -> Int -> Bool) -> T57 -> [T58] -> T57",
  ],
  ["for/until", "(T48 -> T49) -> (T48 -> Bool) -> [T48] -> ()"],
  ["for/until/i", "(T50 -> Int -> T51) -> (T50 -> Int -> Bool) -> [T50] -> ()"],
  ["each/until", "(T49 -> T48) -> (T49 -> Bool) -> [T49] -> [T49]"],
  [
    "each/until/i",
    "(T51 -> Int -> T50) -> (T51 -> Int -> Bool) -> [T51] -> [T51]",
  ],
  ["map/i", "(T37 -> Int -> T36) -> [T37] -> [T36]"],
  ["reduce/i", "(T35 -> T36 -> Int -> T35) -> T35 -> [T36] -> T35"],
  ["filter/i", "(T36 -> Int -> Bool) -> [T36] -> [T36]"],
  ["some/i?", "(T33 -> Int -> Bool) -> [T33] -> Bool"],
  ["every/i?", "(T33 -> Int -> Bool) -> [T33] -> Bool"],
  ["ones", "Int -> [Int]"],
  ["zeroes", "Int -> [Int]"],
  ["ones/int", "Int -> [Int]"],
  ["zeroes/int", "Int -> [Int]"],
  ["ones/float", "Int -> [Float]"],
  ["zeroes/float", "Int -> [Float]"],
  ["positive?", "Int -> Bool"],
  ["negative?", "Int -> Bool"],
  ["invert", "Int -> Int"],
  ["negative-one?", "Int -> Bool"],
  ["divisible?", "Int -> Int -> Bool"],
  ["positive/int?", "Int -> Bool"],
  ["negative/int?", "Int -> Bool"],
  ["invert/int", "Int -> Int"],
  ["negative-one/int?", "Int -> Bool"],
  ["divisible/int?", "Int -> Int -> Bool"],
  ["positive/float?", "Float -> Bool"],
  ["negative/float?", "Float -> Bool"],
  ["invert/float", "Float -> Float"],
  ["negative-one/float?", "Float -> Bool"],
  ["divisible/float?", "Float -> Float -> Bool"],
  ["upper", "Char -> Char"],
  ["lower", "Char -> Char"],
  ["match?", "[Char] -> [Char] -> Bool"],
  ["digit?", "Char -> Bool"],
  ["fill", "Int -> (Int -> T55) -> [T55]"],
  ["max", "Int -> Int -> Int"],
  ["min", "Int -> Int -> Int"],
  ["max/int", "Int -> Int -> Int"],
  ["min/int", "Int -> Int -> Int"],
  ["max/float", "Float -> Float -> Float"],
  ["min/float", "Float -> Float -> Float"],
  ["maximum", "[Int] -> Int"],
  ["minimum", "[Int] -> Int"],
  ["maximum/int", "[Int] -> Int"],
  ["minimum/int", "[Int] -> Int"],
  ["maximum/float", "[Float] -> Float"],
  ["minimum/float", "[Float] -> Float"],
  ["gt?", "Bool -> Bool -> Bool"],
  ["lt?", "Bool -> Bool -> Bool"],
  ["and?", "Bool -> Bool -> Bool"],
  ["or?", "Bool -> Bool -> Bool"],
  ["not?", "Bool -> Bool"],
  ["abs", "Int -> Int"],
  ["abs/int", "Int -> Int"],
  ["abs/float", "Float -> Float"],
  ["first", "[T16] -> T16"],
  ["last", "[T17] -> T17"],
  ["pair", "T16 -> T15 -> {T16 * T15}"],
  ["product", "[Int] -> Int"],
  ["product/int", "[Int] -> Int"],
  ["product/float", "[Float] -> Float"],
  ["sum", "[Int] -> Int"],
  ["sum/int", "[Int] -> Int"],
  ["sum/float", "[Float] -> Float"],
  ["avg", "Int -> Int -> Int"],
  ["avg/int", "Int -> Int -> Int"],
  ["avg/float", "Float -> Float -> Float"],
  ["mean", "[Int] -> Int"],
  ["median", "[Int] -> Int"],
  ["mean/int", "[Int] -> Int"],
  ["mean/float", "[Float] -> Float"],
  ["median/int", "[Int] -> Int"],
  ["median/float", "[Float] -> Float"],
  ["zip", "{[T38] * [T37]} -> [{T38 * T37}]"],
  ["unzip", "[{T45 * T44}] -> {[T45] * [T44]}"],
  ["zip-with", "(T32 -> T34 -> T33) -> [T32] -> [T34] -> [T33]"],
  ["window", "[T74] -> Int -> [[T74]]"],
  ["flat", "[[T60]] -> [T60]"],
  ["enumerate", "[T46] -> [{Int * T46}]"],
  ["clamp", "Int -> Int -> Int"],
  ["clamp-range", "Int -> Int -> Int -> Int"],
  ["clamp/int", "Int -> Int -> Int"],
  ["clamp-range/int", "Int -> Int -> Int -> Int"],
  ["clamp/float", "Float -> Float -> Float"],
  ["clamp-range/float", "Float -> Float -> Float -> Float"],
  ["at", "[T19] -> Int -> T19"],
  ["scan", "(T74 -> T74 -> T74) -> [T74] -> [T74]"],
  ["cycle", "Int -> [T30] -> [T30]"],
  ["replicate", "Int -> T28 -> [T28]"],
  ["cartesian-product", "[T74] -> [T73] -> [{T74 * T73}]"],
  ["lcm", "Int -> Int -> Int"],
  ["gcd", "Int -> Int -> Int"],
  ["delta", "Int -> Int -> Int"],
  ["delta/int", "Int -> Int -> Int"],
  ["delta/float", "Float -> Float -> Float"],
  ["map/adjacent", "(T40 -> T40 -> T41) -> [T40] -> [T41]"],
  ["buckets", "Int -> [[T25]]"],
  ["count/char", "Char -> [Char] -> Int"],
  ["count/int", "Int -> [Int] -> Int"],
  ["count/float", "Float -> [Float] -> Int"],
  ["count/bool", "Bool -> [Bool] -> Int"],
  ["count", "(T39 -> Bool) -> [T39] -> Int"],
  ["points", "(T52 -> Bool) -> [[T52]] -> [[Int]]"],
  ["unique/int", "[Int] -> [Int]"],
  ["unique/char", "[Char] -> [Char]"],
  ["permutation", "[T76] -> [[T76]]"],
  ["combination/pairs", "[T43] -> [{T43 * T43}]"],
  ["combination", "[T63] -> [[T63]]"],
  ["combination/n", "Int -> [T63] -> [[T63]]"],
  ["subset", "[T106] -> [[T106]]"],
  ["in-bounds?", "[T17] -> Int -> Bool"],
  ["take/first", "Int -> [T31] -> [T31]"],
  ["drop/first", "Int -> [T32] -> [T32]"],
  ["take/last", "Int -> [T33] -> [T33]"],
  ["drop/last", "Int -> [T32] -> [T32]"],
  ["true/option", "T15 -> {Bool * T15}"],
  ["false/option", "T15 -> {Bool * T15}"],
  ["resolve/option", "([T58] -> T59) -> T59 -> [{Bool * T58}] -> {Bool * T59}"],
  ["call", "(T20 -> T21) -> T20 -> T21"],
  ["copy", "[T37] -> [T37]"],
  ["sort", "(T97 -> T97 -> Bool) -> [T97] -> [T97]"],
  [
    "neighborhood",
    "[[Int]] -> Int -> Int -> (T58 -> [Int] -> Int -> Int -> ()) -> [[T58]] -> ()",
  ],
  ["neighborhood/moore", "[[Int]]"],
  ["neighborhood/diagonal", "[[Int]]"],
  ["neighborhood/kernel", "[[Int]]"],
  ["neighborhood/von-neumann", "[[Int]]"],
  ["group", "(T191 -> [Char]) -> [T191] -> [[[{[Char] * [T191]}]]]"],
  ["append!", "T20 -> [T20] -> [T20]"],
  ["tail", "[T32] -> [T32]"],
  ["head", "[T32] -> [T32]"],
  ["fp/mul", "Int -> Int -> Int"],
  ["fp/div", "Int -> Int -> Int"],
  ["fp/add", "Int -> Int -> Int"],
  ["fp/sub", "Int -> Int -> Int"],
  ["fp/emod", "Int -> Int -> Int"],
  ["fp/mod", "Int -> Int -> Int"],
  ["cond/dispatch", "(T18 -> Bool) -> T19 -> T19 -> T18 -> T19"],
  ["split", "[Char] -> [Char] -> [[Char]]"],
  ["Tuple/swap", "{T21 * T20} -> {T20 * T21}"],
  ["Tuple/map/fst", "{T21 * T23} -> (T21 -> T22) -> T22"],
  ["Tuple/map/snd", "{T23 * T22} -> (T22 -> T21) -> T21"],
  ["Tuple/map", "{T25 * T26} -> (T25 -> T26 -> T24) -> T24"],
  ["Tuple/map/fst", "{T21 * T22} -> (T21 -> T23) -> T23"],
  ["Tuple/map/snd", "{T22 * T23} -> (T23 -> T21) -> T21"],
  ["Vector->Tuple", "(T25 -> T26) -> (T25 -> T24) -> T25 -> {T26 * T24}"],
  ["Tuple/int/add", "{Int * Int} -> Int"],
  ["Tuple/int/sub", "{Int * Int} -> Int"],
  ["Tuple/int/mul", "{Int * Int} -> Int"],
  ["Tuple/int/div", "{Int * Int} -> Int"],
  ["Tuple/bool/eq?", "{Bool * Bool} -> Bool"],
  ["Tuple/int/eq?", "{Int * Int} -> Bool"],
  ["Tuple/char/eq?", "{Char * Char} -> Bool"],
  ["Tuple/float/eq?", "{Float * Float} -> Bool"],
  ["Tuple/bool/not-eq?", "{Bool * Bool} -> Bool"],
  ["Tuple/int/not-eq?", "{Int * Int} -> Bool"],
  ["Tuple/char/not-eq?", "{Char * Char} -> Bool"],
  ["Tuple/float/not-eq?", "{Float * Float} -> Bool"],
  ["Int->Alphabet", "Int -> Char -> Char"],
  ["Integer->Chars", "Int -> [Char]"],
  ["Integer->String", "Int -> [Char]"],
  ["Float->Chars", "Float -> [Char]"],
  ["Float->String", "Float -> [Char]"],
  ["String->Vector", "Char -> [Char] -> [[Char]]"],
  ["Vector->String", "Char -> [[Char]] -> [Char]"],
  ["Chars->Digits", "[Char] -> [Int]"],
  ["Digits->Integer", "[Int] -> Int"],
  ["Chars->Integer", "[Char] -> Int"],
  ["String->Integer", "[Char] -> Int"],
  ["String->Float", "[Char] -> Float"],
  ["Chars->Float", "[Char] -> Float"],
  ["Integer->Bits", "Int -> [Int]"],
  ["Char->Digit", "Char -> Int"],
  ["Digit->Char", "Int -> Char"],
  ["Integer->Digits", "Int -> [Int]"],
  ["Digits->Chars", "[Int] -> [Char]"],
  ["Set->Vector", "[[[T79]]] -> [[T79]]"],
  ["Vector->Set", "[[Char]] -> [[[Char]]]"],
  ["Vector/equal?", "[Int] -> [Int] -> Bool"],
  ["Set/size", "[[T63]] -> Int"],
  ["Table/size", "[[T63]] -> Int"],
  ["Set/new", "() -> [[T25]]"],
  ["Table/new", "() -> [[T25]]"],
  ["Set/intersection", "[[[Char]]] -> [[[Char]]] -> [[[Char]]]"],
  ["Set/difference", "[[[Char]]] -> [[[Char]]] -> [[[Char]]]"],
  ["Set/xor", "[[[Char]]] -> [[[Char]]] -> [[[Char]]]"],
  ["Set/union", "[[[Char]]] -> [[[Char]]] -> [[[Char]]]"],
  ["Set/add!", "[Char] -> [[[Char]]] -> ()"],
  ["Set/remove!", "[Char] -> [[[Char]]] -> ()"],
  ["Set/has?", "[Char] -> [[[Char]]] -> Bool"],
  ["Table/entries", "[[[{T85 * T86}]]] -> [{T85 * T86}]"],
  ["Table/keys", "[[[{T82 * T83}]]] -> [T82]"],
  ["Table/values", "[[[{T83 * T82}]]] -> [T82]"],
  ["Set/values", "[[T60]] -> [T60]"],
  ["Table/get", "[Char] -> [[[{[Char] * T104}]]] -> [{[Char] * T104}]"],
  ["Table/get*", "[Char] -> [[[{[Char] * T138}]]] -> {Bool * [T138]}"],
  ["Table/get!", "[Char] -> [[[{[Char] * T107}]]] -> T107"],
  ["Table/has?", "[Char] -> [[[{[Char] * T115}]]] -> Bool"],
  ["Table/set!", "[Char] -> T107 -> [[[{[Char] * T107}]]] -> ()"],
  ["Table/remove!", "[Char] -> [[[{[Char] * T112}]]] -> ()"],
  ["Table/count", "[[Char]] -> [[[{[Char] * Int}]]]"],
  ["Table/drop!", "[[Char]] -> [[[{[Char] * T119}]]] -> ()"],
  [
    "Table/keep",
    "[[Char]] -> [[[{[Char] * T147}]]] -> [[[{[Char] * [Char]}]]]",
  ],
  ["Table/omit", "[[Char]] -> [[[{[Char] * T140}]]] -> [[[{[Char] * T140}]]]"],
  ["Table/merge!", "[[[{[Char] * T189}]]] -> [[[{[Char] * T189}]]] -> ()"],
  [
    "Table/merge",
    "[[[{[Char] * T207}]]] -> [[[{[Char] * T207}]]] -> [[[{[Char] * T207}]]]",
  ],
  ["Que/new", "T16 -> [[T16]]"],
  ["Que/empty?", "[[T21]] -> Bool"],
  ["Que/not-empty?", "[[T23]] -> Bool"],
  ["Que/empty!", "[[T23]] -> ()"],
  ["Que/enque!", "T29 -> [[T29]] -> ()"],
  ["Que/deque!", "[[T140]] -> ()"],
  ["Que/peek", "[[T26]] -> T26"],
  ["Que/push!", "T26 -> [[T26]] -> ()"],
  ["Que/pop!", "[[T140]] -> ()"],
  ["Que/prepend!", "T26 -> [[T26]] -> ()"],
  ["Que/first", "[[T26]] -> T26"],
  ["Que/last", "[[T32]] -> T32"],
  ["Que/tail!", "[[T140]] -> ()"],
  ["Que/append!", "T26 -> [[T26]] -> ()"],
  ["Vector->Que", "[T67] -> [[T67]]"],
  ["Que->Vector", "[[T60]] -> [T60]"],
  ["Que/get", "[[T24]] -> Int -> T24"],
  ["Que/length", "[[T19]] -> Int"],
  ["Que/at", "Int -> [[T28]] -> T28"],
  ["BigInt/add", "[Int] -> [Int] -> [Int]"],
  ["BigInt/sub", "[Int] -> [Int] -> [Int]"],
  ["BigInt/mul", "[Int] -> [Int] -> [Int]"],
  ["BigInt/lte?", "[Int] -> [Int] -> Bool"],
  ["BigInt/gte?", "[Int] -> [Int] -> Bool"],
  ["BigInt/lt?", "[Int] -> [Int] -> Bool"],
  ["BigInt/gt?", "[Int] -> [Int] -> Bool"],
  ["BigInt/equal?", "[Int] -> [Int] -> Bool"],
  ["BigInt/div", "[Int] -> [Int] -> [Int]"],
  ["BigInt/square", "[Int] -> [Int]"],
  ["BigInt/div/floor", "[Int] -> [Int] -> [Int]"],
  ["BigInt/div/ceal", "[Int] -> [Int] -> [Int]"],
  ["BigInt/sum", "[[Int]] -> [Int]"],
  ["BigInt/product", "[[Int]] -> [Int]"],
  ["BigInt/new", "[Char] -> [Int]"],
  ["BigInt/pow", "[Int] -> Int -> [Int]"],
  ["BigInt/expt", "[Int] -> [Int] -> [Int]"],
  ["BigInt/range", "Int -> Int -> [[Int]]"],
  ["Vector/push!", "[T22] -> T22 -> [T22]"],
  ["Vector/pop!", "[T16] -> ()"],
  ["Vector/last", "[T17] -> T17"],
  ["Vector/first", "[T16] -> T16"],
  ["Vector/pull!", "[T20] -> T20"],
  ["Vector/get!", "Int -> [T16] -> T16"],
  ["Vector/get*", "Int -> [T18] -> {Bool * [T18]}"],
  ["Vector/at!", "Int -> [T21] -> T21"],
  ["Vector/at*", "Int -> [T23] -> {Bool * [T23]}"],
  ["Vector/set!", "[T18] -> Int -> T18 -> ()"],
  ["Vector/length", "[T16] -> Int"],
  ["Vector/append!", "T27 -> [T27] -> [T27]"],
  ["Vector/2d/set!", "[T22] -> [T22] -> ()"],
  ["Vector/2d/add", "[Int] -> [Int] -> [Int]"],
  ["Vector/2d/sub", "[Int] -> [Int] -> [Int]"],
  ["Vector/2d/mul", "[Int] -> [Int] -> [Int]"],
  ["Vector/2d/div", "[Int] -> [Int] -> [Int]"],
  ["Vector/2d/mag/sqrt", "[Int] -> Int"],
  ["Vector/2d/mag", "[Int] -> Int"],
  ["Vector/2d/dot", "[Int] -> [Int] -> Int"],
  ["Vector/2d/cross", "[Int] -> [Int] -> [Int]"],
  ["Vector/2d/dist", "[Int] -> [Int] -> Int"],
  ["Vector/2d/norm", "[Int] -> [Int]"],
  ["Vector/2d/limit", "[Int] -> Int -> [Int]"],
  ["Vector/2d/add!", "[Int] -> [Int] -> ()"],
  ["Vector/2d/sub!", "[Int] -> [Int] -> ()"],
  ["Vector/2d/mul!", "[Int] -> [Int] -> ()"],
  ["Vector/2d/div!", "[Int] -> [Int] -> ()"],
  ["Vector/2d/norm!", "[Int] -> ()"],
  ["Vector/2d/limit!", "[Int] -> Int -> ()"],
  ["Vector/2d/mag!", "[Int] -> [Int] -> ()"],
  ["Vector/3d/set!", "[T24] -> [T24] -> ()"],
  ["Vector/3d/add", "[Int] -> [Int] -> [Int]"],
  ["Vector/3d/sub", "[Int] -> [Int] -> [Int]"],
  ["Vector/3d/mul", "[Int] -> [Int] -> [Int]"],
  ["Vector/3d/div", "[Int] -> [Int] -> [Int]"],
  ["Vector/3d/mag/sqrt", "[Int] -> Int"],
  ["Vector/3d/mag", "[Int] -> Int"],
  ["Vector/3d/dot", "[Int] -> [Int] -> Int"],
  ["Vector/3d/cross", "[Int] -> [Int] -> [Int]"],
  ["Vector/3d/dist", "[Int] -> [Int] -> Int"],
  ["Vector/3d/norm", "[Int] -> [Int]"],
  ["Vector/3d/limit", "[Int] -> Int -> [Int]"],
  ["Vector/3d/add!", "[Int] -> [Int] -> ()"],
  ["Vector/3d/sub!", "[Int] -> [Int] -> ()"],
  ["Vector/3d/mul!", "[Int] -> [Int] -> ()"],
  ["Vector/3d/div!", "[Int] -> [Int] -> ()"],
  ["Vector/3d/norm!", "[Int] -> ()"],
  ["Vector/3d/limit!", "[Int] -> Int -> ()"],
  ["Vector/3d/mag!", "[Int] -> [Int] -> ()"],
  ["Vector/new", "(Int -> T57) -> Int -> [T57]"],
  ["Matrix/new", "(Int -> Int -> T45) -> Int -> Int -> [[T45]]"],
  ["String/equal?", "[Char] -> [Char] -> Bool"],
  ["String/equal?", "[Char] -> [Char] -> Bool"],
  ["String/lte?", "[Char] -> [Char] -> Bool"],
  ["String/gte?", "[Char] -> [Char] -> Bool"],
  ["String/lt?", "[Char] -> [Char] -> Bool"],
  ["String/gt?", "[Char] -> [Char] -> Bool"],
  ["Char/eq?", "Char -> Char -> Bool"],
  ["Int/eq?", "Int -> Int -> Bool"],
  ["Bool/eq?", "Bool -> Bool -> Bool"],
  ["Float/eq?", "Float -> Float -> Bool"],
].map(
  ([name, signature]) => ({
    name,
    signature: signature.replaceAll(/\d+/g, ""),
  }),
  []
);
